### ISSUE TITLE
How to add a missing OSX framework?

### ISSUE THREAD

**Issue by phuesler** [LubosD/darling#83]
I'm trying to get [atos](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/atos.1.html) to work on Ubuntu, but it is missing several libs and frameworks. How would I got about adding them?

````
phuesler@phuesler-VirtualBox:~/Desktop$ dyldd atos
Resolving dependencies of /home/phuesler/Desktop/atos

/System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication => not found
/System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication => not found
/usr/lib/libxcselect.dylib => not found
/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation => libFoundation.so
/System/Library/Frameworks/Security.framework/Versions/A/Security => libCoreSecurity.so
/usr/lib/libobjc.A.dylib => libobjcdarwin.so
/usr/lib/libSystem.B.dylib => libSystem.so
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation => libCoreFoundation.so
````

**Comment by dequis** [comment]
There's documentation for that here: http://www.darlinghq.org/for-developers/implementing-new-frameworks-from-scratch

Good luck!

**Comment by ceinem** [comment]
Hi, sorry for digging out this ancient issue. Is there maybe some updated documentation, as your link is unfortunately broken. I'm trying to add some very niche frameworks, in order to get some of my favorite apps running.

**Comment by CuriousTommy** [comment]
Hi @ceinem,

You can find the instruction here: https://docs.darlinghq.org/contributing/generating-stubs.html
