### ISSUE TITLE
Debian repo please!

### ISSUE THREAD

**Issue by haze007** [LubosD/darling#84]
I understand there's a PPA for Ubuntu and I tried possible way to get the PPA work on Debian. The GNUstep-common along with some version name was never installing. It'll be better if you give me a hint as to how I can install it on Debian. I'm using the Debian testing repo.

**Comment by LubosD** [comment]
This is an issue tracker, not a discussion forum.

As far as installation is concerned, refer to build instructions of Darling and respective dependencies.
