### ISSUE TITLE
freequartz integration

### ISSUE THREAD

**Issue by ryao** [LubosD/darling#91]
It seems that someone wrote a cross platform implementation of Apple's CoreGraphics API:

https://code.google.com/p/freequartz/

If someone were to integrate it, it could become possible to run CoreGraphics applications in Darling.

**Comment by LubosD** [comment]
Sorry to say that, but you can't make things work by integrating random half-baked libraries.

Moreover, CoreGraphics is only used for low level drawing. It doesn't bring you that much closer to running GUI apps.
